"""add_raw_content_remove_file_path_add_source_references

Revision ID: 4fe6761c0ac4
Revises: 
Create Date: 2026-06-07 19:55:43.919962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4fe6761c0ac4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_references',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=8), nullable=False),
    sa.Column('doc_id', sa.String(length=8), nullable=False),
    sa.Column('cited_text', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('raw_content', sa.Text(), nullable=True, comment='原始 Markdown 全文'))
    op.alter_column('documents', 'doc_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='comment',
               existing_nullable=False)
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.alter_column('documents', 'doc_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='comment',
               existing_nullable=False)
    op.drop_column('documents', 'raw_content')
    op.drop_table('source_references')
    # ### end Alembic commands ###
